language: php

sudo: false

php:
  - 7.4
  - 8.0

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - php bin/benchmark --iteration=3 --rows=65534 --cells=5 --driver=Spout
  - php bin/benchmark --iteration=3 --rows=65534 --cells=5 --driver=SpreadsheetExcelWriter
  - php bin/benchmark --iteration=3 --rows=65534 --cells=5 --driver=Phpspreadsheet
